# Generated by Django 4.2.7 on 2023-12-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_task'),
        ('task', '0002_alter_task_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Categories',
            field=models.ManyToManyField(to='category.category'),
        ),
    ]
